
dependencies:
  flutter:
    sdk: flutter
  # .. ( Logic Packages ) ..
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.4
  equatable: ^2.0.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  formz: ^0.4.1
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  keyboard_dismisser: ^3.0.0
  flutter_native_splash: ^2.2.3
  firebase_messaging: ^11.4.4
  firebase_core: ^1.18.0  
  flutter_local_notifications: ^9.6.1
  analyzer: ^4.6.0
  
  # .. ( Assets Packages ) ..
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  iconify_flutter: ^0.0.4

  lottie: ^1.3.0
  flutter_svg: ^1.1.0
  go_router: ^3.1.1
  json_annotation: 4.5.0

  # .. ( UI Packages ) ..
  pin_code_fields: ^7.4.0
  flutter_dialogs: ^3.0.0
  flutter_staggered_grid_view: ^0.6.1
  carousel_slider: ^4.1.1
  expandable: ^5.0.1
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.3
  percent_indicator: ^4.2.2

  # .. ( Custom Packages ) ..
  flutter_extension_pk:
    git:
      url: https://github.com/geeks-code-com/flutter_extension_pk.git
      ref: version-2.0.0
  geeks_theme:
    git:
      url: https://github.com/geeks-code-com/geeks_theme.git
      # ref: main
  geeks_service:
    git:
      url: https://github.com/geeks-code-com/geeks_service.git
      ref: e66d236
  geeks_widgets:
    git:
      url: https://github.com/geeks-code-com/geeks_widgets.git
      ref: '44ab1de'